name: Deploy AKS Monitoring Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
          environment: azurecloud

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        if: success() && steps.plan.conclusion == 'success'
        run: terraform apply -input=false -auto-approve tfplan
